### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by vablings** [zkxjzmswkwl/Carnival#20]
we need a logo

**Comment by toinouH** [comment]
We still have the one from the circus public repo unless it was sold as an asset.

**Comment by vablings** [comment]
is there a SVG of it available? can use it as a placeholder at least

**Comment by zkxjzmswkwl** [comment]
Branding wasn't in the contract whatsoever - can be used. I'll see if I can dig it up

**Comment by zkxjzmswkwl** [comment]
For convenience, here's a link to an `<svg>` element.
https://p.ryswick.net/p/rHE5lL.html

Assets will be included in the next commit at `carnival-web/assets`.
