### ISSUE TITLE
Remove serde_json, move state restoration logic to use toml.

### ISSUE THREAD

**Issue by zkxjzmswkwl** [zkxjzmswkwl/Carnival#4]
TOML seems more appropriate for a configuration file and things of that nature, so I'll be including support for that anyway. 

I don't see the point in supporting two key/value storage formats.

**Comment by vablings** [comment]
https://github.com/zkxjzmswkwl/Carnival/pull/6

**Comment by zkxjzmswkwl** [comment]
Closed with #6
